apiVersion: gateway.networking.k8s.io/v1
kind: ReferenceGrant
metadata:
  name: outpost
  namespace: authentik
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: garage
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: qbit
  to:
    - group: ""
      kind: Service
      name: authentik-server
