apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: authentik
  namespace: postgres
spec:
  cluster:
    name: postgres
  databaseReclaimPolicy: retain
  name: authentik
  owner: authentik
