apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # add-ons
  - add-ons/gateway-api.yaml
  - add-ons/traefik.yaml
  - add-ons/cert-manager.yaml
  - add-ons/sealed-secrets.yaml
  - add-ons/cnpg.yaml
  # services
  - services/app-argocd-repos.yaml
  - services/app-autoregexbot.yaml
  - services/app-betterslcm.yaml
  - services/app-jellyfin.yaml
  - services/app-legislative-summarization.yaml
  - services/app-scriptscribe.yaml
  - services/app-seaweedfs.yaml
  - services/app-qbit.yaml
  - services/app-stirling-pdf.yaml
