apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stirling-pdf
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://docs.stirlingpdf.com/Stirling-PDF-chart
      chart: stirling-pdf-chart
      targetRevision: "3.1.0"
      helm:
        values: |
          fullnameOverride: stirling-pdf
          persistence:
            enabled: true
            size: 512Mi
          deployment:
            extraVolumeMounts:
              - name: storage-volume
                mountPath: /configs
          probes:
            liveness:
              initialDelaySeconds: 90
            readiness:
              initialDelaySeconds: 60
    - repoURL: https://gitea.whyredfire.dev/whyredfire/gitops.git
      targetRevision: main
      path: extras/services/stirling-pdf
  destination:
    server: https://kubernetes.default.svc
    namespace: stirling-pdf
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
