apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seaweedfs
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://seaweedfs.github.io/seaweedfs/helm
      chart: seaweedfs
      targetRevision: 4.33.0
      helm:
        values: |
          allInOne:
            enabled: true
          master:
            enabled: false
          volume:
            enabled: false
          filer:
            enabled: false
    - repoURL: https://gitea.whyredfire.dev/whyredfire/gitops.git
      targetRevision: main
      path: extras/services/seaweedfs
  destination:
    server: https://kubernetes.default.svc
    namespace: seaweedfs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
