apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-repos
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://gitea.whyredfire.dev/whyredfire/gitops.git
    targetRevision: main
    path: extras/add-ons/argocd-repos
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
