apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster.yaml
  - authentik-db-sealedsecret.yaml
  - authentik-database.yaml
  - grafana-db-sealedsecret.yaml
  - grafana-database.yaml
  - legislative-db-sealedsecret.yaml
  - legislative-database.yaml
  - redoost-db-sealedsecret.yaml
  - redoost-database.yaml
