---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: legislative-db
  namespace: postgres
spec:
  encryptedData:
    password: AgBrNoWz81KBlhRhS3TurgSfi7tpbTJk5FdwO6ex5B69nsAWtEEqBR+eB5RzxP/IRFxIXAqV65Ui6o5UspGiHMg9aSmnqFHPgg4hZ5qTRxYa0AIalIDEXz7LF2OoBZxqXOZT9EkJ1cDI0LzG+pcU09+1deM5M15PtdMvDhmHuySIok2QsDF9YSy2TeaT2uzVzQt4qFnmJ1ZmdK49EVBX0cH78CsJFxaSVWn/u+0ZTZeMKe0gcNpR7sF8vGb9FZMlHMvdyIRnqObLwvckfhTKEsmlgkN4FgPLRpdgr3e+sOb1iiMMfrSdjhU3qQHib3xKfFV9/En6SqMQPKjsamMVlV9i91jCE8WGL5IoWEt+YTjqtu4Zg3lqqWHKwhgzB13TzMe35unmjoeZcofHk5GXIOAVnVBcOL0KsXrHSOjPihtKvf9uWdDMu3ovhiLBcPOJgP6Dd3GXe/frgQPg12HpauxTpl6LRGwEfxxhaGWMth8TyUrZ7JG9nIndc9nzY047J9ufNCdabj7xMNhUVk6WynOkzffGWUBA7fWHl5lSQK1X/8QVN0CDh5GWfP6uHEzYgpx4nmnZunTH7r32E717UdRAkpP43Rl6nOzfZ0pTeFPgjHrTVSdYhtf3JwJC73KcnJTGciq/QGYewMeymV5JMashkTtT28Wqhf412GiH4Zn/DZomVMAL37ROUSN9lZz78ZV9U5EKoqget9+bgqmYKrNchFVhL91WKj8O8c4479wAYjqiBpTIfEZal6wC+sNpuyuMwZrGrv3fK/PTmxxHXeHH
    username: AgCmCEl/g9Cuc0tBEXmZHsJrL5greGBglWJQbJFR+6bWA0+gcwU7rcrY3v1t5oET8W+ytw0Kfuun3OqbatgP8/ztaVkt8lm9nFq30gF4AlBBy0nC6KkcKyUGfrhcpHJmzabkcuu6cXZAEf+IVsFBPSeXU/jvZmAXzwdcIMC/nHRF6NHbl+ZM3e6DKquF+ocalsp8Z9UbacIsgjA8jkYaBxij2qiWHTzrLluDTUCofkrEAH80+cJ5WAqR4jWf1lh5t9u6shj+iDCw2WsShjn5dEm1E1hPIaORcJ4qBbYvmIwyvS4yI3k5FIb78fYPfDFWq3F4J+v1+wjn79kQQUhEVwFNbZtcAtTgBYkKv6Z7QfcjwWeSK4Bv6E7bc8QusFVklL9tUrzstPYbNwoP77inWAQ6OtUjdDz6YnDMMRSKkLqOlty5HO4PZGuZ6i/eedGGrSTzsM+kVT4z4ikP7uiFdDLANuXs89rRRD7o5YKIzraDTVC3FytXOEReebHSh9uHLUpNrlvi1Ih9wl/fNx9GAQtUinu4zmq3QD/97ZW3egeVMhB4YD69tp/2lMiVIfFwCxvCPPqfiv8tbwEQmNi/6JD4gcuu3slYaToKMzVjdNkFpTuTRyCGfcssLTm2iRXla3cUmXJqX9+A9lg3fWGAGpw/zG0nSJ51oOfau7ON33ZT/rFll1jcqI9DfZsuQ5XFRtYlZ1+rKm6xDDWY+A==
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: legislative-db
      namespace: postgres
    type: kubernetes.io/basic-auth
