apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: legislative
  namespace: postgres
spec:
  cluster:
    name: postgres
  databaseReclaimPolicy: retain
  name: legislative
  owner: legislative
