---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redoost-db
  namespace: postgres
spec:
  encryptedData:
    password: AgBOLny607zrRCeoMDQkT5uN/5kB1W74ju1cufJiyqiCtLtnhEJjD57/9FXg8ic21YrrjWBdHaWxv5Sonz3CY6m6OC/pF2t/7pBDq/Yw63PT5bx8TLvOXLwb+2cb7boo52k0kFm0MpA3GIktIsx1GQjuPAl7KdeotAnaKSUQkH3I8IAF+v+njpWFS7nrQJnz+NHvlmKLT8hD8SFC7NPCYz0awXJ/CENJKKdQuFtTXh3YBV0BignILIAUR047Nqzg//dxOCT2DUuxFLyddt4iFmUCq7bpLxD1HWceS0Vsts3cXto9AObkjNXHKAVb0SGpGv3dJg6tfqb5Yls+zSxfIiDFzUVkwsV6/SCEdfEhAPShRBiqDu7Dv6G1+8NbcFujCat3TDNw50pZqwCuETvqdlyO39VdQ4P2Eecz2APYjDlZMCsulgdB4co/x7Ix+pzexCVhxWKc11A59crwIie+RdHmPT6yEew337P8ojU2p0H9NzbJheEQBhSLrlQ38Mpm/YdYN25fu2WislqxkrsJ3QdtOliEsWqBgV3TOTbYYt9vWE4Y+psg7SHcka+YsX8nuw72ouc7CIK5hvJkMa/qM0bW3WghQFbEHs0IdSiYmpQhbwPrXPexPO5vmzUJstiKwUB0wDtsyfXlWr/imySdjLt6lNSjQk3awf4fO5HLofcVO/zxtg1lAaLZWl5FVP8dW3Wh97Yfla10uIOWALUXTEw7TnePHqLe3G+FrcHjOMAebt/FJrc4P48GeXRve5SpAR1hKOG9s+7ARydrWKdrb8Sv
    username: AgBOzETvCTrajt+s4rPrmfB15lzQGIDTv5ArvaDLAnUf6cP4MdikbypuNyieT5YVpAXiUpVJqUefHRUkONxcvq51iFd/NKE7K6VCv0i8xQVgrmX55fgc5FCB1VkNDilFxQhDp1DBIl+oCpGSS8AafkKKXECoGDdvG3ldj5i6Us0jDD3EyjPayZGPV6ULeABTbFWodAOBeieKs4WzCS1Npyz0rzGqoj4H9dW6LnDZlCGPq8sL6rkP85DceatKUyzmSSxhDMWsuwL0TLpQBeQnLr06G3uQlZHvUp/PiAykqjXz8/YW/HQZzFm0GOJmiKTtv99J9ErnJ9iriMFrGsfNnv0jAhXSmwy8EGlo7WkzstVQGtwFCKKQtG2l9GavHh0nlOIaFYriB2WFRaujJVMgqTDcVrP1qX6uozqwblDXuYYJ8KFsbSJC3stGECc26kL1MmpyGihsCIh9bXPEg6DANi25amcjR0OVImGPEDlOQitWEdJ76CjqiPt2ehrFin7BF3dg6DK3fsRR7KkCXQHyTRR6RnJ/7Nl7zLOCMUl5WFltUIRApT2EGAgVLiSMpFC5ITw2OFAvKeSjqOlSo3FdMlX8lSkQXGBjeIGb9t9bpMAyLh/PoqfB5hyCQxfV3CE4nUJkrpL78BqbozUOG8tnz9kWri2LCAn7+k+dSYnOoimHDfG+YxAImgoI/k4rqnHLAKknHjtnbm20
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: redoost-db
      namespace: postgres
    type: kubernetes.io/basic-auth
