apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # add-ons
  - add-ons/gateway-api.yaml
  - add-ons/traefik.yaml
  - add-ons/cert-manager.yaml
  - add-ons/anubis-operator.yaml
  - add-ons/sealed-secrets.yaml
  - add-ons/cnpg.yaml
  - add-ons/argocd-repos.yaml
  # services
  - services/autoregexbot.yaml
  - services/betterslcm.yaml
  - services/jellyfin.yaml
  - services/legislative-summarization.yaml
  - services/scriptscribe.yaml
  - services/seaweedfs.yaml
  - services/qbit.yaml
  - services/stirling-pdf.yaml
