apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: jellyfin
  namespace: argocd
spec:
  destination:
    namespace: jellyfin
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: jellyfin
      helm:
        values: |
          service:
            type: ClusterIP
            port: 8096
          ingress:
            enabled: false
          persistence:
            config:
              enabled: true
              size: 2Gi
            media:
              enabled: true
              type: hostPath
              hostPath: /srv/media
      repoURL: https://jellyfin.github.io/jellyfin-helm
      targetRevision: 2.7.0
    - path: apps/jellyfin
      repoURL: https://gitea.whyredfire.dev/whyredfire/gitops.git
      targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
