apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - autoregexbot.yaml
  - bentopdf.yaml
  - betterslcm.yaml
  - garage.yaml
  - garage-ui.yaml
  - jellyfin.yaml
  - legislative-summarization.yaml
  - qbit.yaml
  - scriptscribe.yaml
