apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: seaweedfs
  namespace: argocd
spec:
  destination:
    namespace: seaweedfs
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: seaweedfs
      helm:
        values: |
          allInOne:
            enabled: true
          master:
            enabled: false
          volume:
            enabled: false
          filer:
            enabled: false
      repoURL: https://seaweedfs.github.io/seaweedfs/helm
      targetRevision: 4.33.0
    - path: apps/seaweedfs
      repoURL: https://gitea.whyredfire.dev/whyredfire/gitops.git
      targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
