apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: stirling-pdf
  namespace: argocd
spec:
  destination:
    namespace: stirling-pdf
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: stirling-pdf-chart
      helm:
        values: |
          fullnameOverride: stirling-pdf
          persistence:
            enabled: true
            size: 512Mi
          deployment:
            extraVolumeMounts:
              - name: storage-volume
                mountPath: /configs
          probes:
            liveness:
              initialDelaySeconds: 90
            readiness:
              initialDelaySeconds: 60
      repoURL: https://docs.stirlingpdf.com/Stirling-PDF-chart
      targetRevision: 3.1.0
    - path: apps/stirling-pdf
      repoURL: https://gitea.whyredfire.dev/whyredfire/gitops.git
      targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
