apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: anubis-operator
  namespace: argocd
spec:
  destination:
    namespace: anubis-operator-system
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
      images:
        - public-registry.brunobernard.dev/techarohq/anubis-operator=ghcr.io/eznix86/anubis-kubernetes-operator:0.4.4
    path: config/default
    repoURL: https://github.com/eznix86/anubis-kubernetes-operator.git
    targetRevision: v0.4.4
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
