apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - alloy.yaml
  - argocd-dashboard.yaml
  - authentik.yaml
  - cert-manager.yaml
  - cnpg.yaml
  - kube-prometheus-stack.yaml
  - loki.yaml
  - postgres.yaml
  - sealed-secrets.yaml
  - traefik.yaml
