apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - anubis-operator.yaml
  - argocd-repos.yaml
  - cert-manager.yaml
  - cnpg.yaml
  - gateway-api.yaml
  - sealed-secrets.yaml
  - traefik.yaml
