apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: https://traefik.github.io/charts
      chart: traefik
      targetRevision: 41.2.0
      helm:
        values: |
          providers:
            kubernetesGateway:
              enabled: true
            kubernetesIngress:
              enabled: false
          service:
            spec:
              type: ClusterIP
              externalIPs:
                - 192.168.2.5
          gateway:
            listeners:
              web:
                namespacePolicy:
                  from: All
              websecure:
                port: 8443
                protocol: HTTPS
                mode: Terminate
                hostname: "*.whyredfire.dev"
                namespacePolicy:
                  from: All
                certificateRefs:
                  - kind: Secret
                    name: wildcard-whyredfire-dev
                    group: ""
    - repoURL: https://gitea.whyredfire.dev/whyredfire/gitops.git
      targetRevision: main
      path: infra/traefik
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
