apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: traefik
  namespace: argocd
spec:
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: traefik
      helm:
        values: |
          ingressClass:
            enabled: false
          providers:
            kubernetesGateway:
              enabled: true
            kubernetesIngress:
              enabled: false
          service:
            spec:
              type: ClusterIP
              externalIPs:
                - 192.168.2.5
          gateway:
            listeners:
              web:
                namespacePolicy:
                  from: All
              websecure:
                port: 8443
                protocol: HTTPS
                mode: Terminate
                hostname: "*.whyredfire.dev"
                namespacePolicy:
                  from: All
                certificateRefs:
                  - kind: Secret
                    name: wildcard-whyredfire-dev
                    group: ""
              websecure-dpdns:
                port: 8443
                protocol: HTTPS
                mode: Terminate
                hostname: "*.whyredfire.dpdns.org"
                namespacePolicy:
                  from: All
                certificateRefs:
                  - kind: Secret
                    name: wildcard-whyredfire-dpdns-org
                    group: ""
      repoURL: https://traefik.github.io/charts
      targetRevision: 41.6.0
    - path: infra/traefik
      repoURL: https://gitea.whyredfire.dev/whyredfire/gitops.git
      targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
