---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redoost-db
  namespace: redoost
spec:
  encryptedData:
    REDOOST_DATABASE_URL: AgAhLopkno58mbcOJtZmrUPMu3RNBSiGK3GH1XRPTgIFxXwtbZhcavqHcZr8cqJQetlpoyLsHptzrusTcBjmCHUT0x5muKDybGbnWb11CgrNRy6TpTSo5y8lY8Ont66huL5FHmz/Mvl2hGcXOG/puk6aIvSDyJhq10fh5XJuUuzB9Nl7PTF4wRmrGn3rZbiDHHiyY5B0Hw/syXsVT2wyi/xI7YVBF30EgKZTjNLJXckGiwI8qewk/H+N2U92e0lm38iglw3OSxjRg6U/7YoWmQmRu5tS98tgml1e7Ib96q3l2+RSfrSAsEzWpemcgJIMUv5FM+Je7u6T9FWujGA3UzLRjvVKdkWlkkhoyLdjWqYII4nfREs4K3GyLok0U0x61LPgu5S/xhWeku67evgZow+PwFxAXB+umurwQhn9+YLguuEec0mXTAMPeacxA4ElRUDeHaKP+U3nPPa0kakCuqxsu2N3gqZeRJlca4npUK8QsFzHowysmTUPXZJ3OnthVBKCfZCMKWNGKd4UgKUsqj8ubcfZYwwjdSHpqMtZ6U+IKnTWxUe8Uz52at4p3GmQj3Dt2wLKfMsWg7NEzz6yXjFMC1o9dsU2CetinQ/1yhLkCFl5UtRQveC9K14MnzN9jJovGyFOqh6hR6/kJKTG70dWh1jm1DGa3uPcN6IEFYc7xl67CcLNr6Qq6I0uG0yqh9HkJZAfVc3Z+EGHRnxyqh60G/1j/ZFIRWrBMJFP6N2JcNxpu0nd32d9BJRzjhgCLQjKdu9jF8Y4HktWLtSIl+jFSJ9PVKZZHLmWsenTx1ml+J1csiO9GnQpT2Xol8114cTlehnws3IEmo54DnIZdoP/lW+McWAoB6ZgPvOIi7Ft5LNCW4BDfhFdFIw3J+jNLn2i
  template:
    metadata:
      name: redoost-db
      namespace: redoost
    type: Opaque
