apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: v39.0.2
    helm:
      values: |
        providers:
          kubernetesGateway:
            enabled: true
          kubernetesIngress:
            enabled: false
        service:
          type: ClusterIP
          externalIPs:
            - 192.168.2.5
        gateway:
          listeners:
            web:
              namespacePolicy:
                from: All
            websecure-dev:
              port: 8443
              protocol: HTTPS
              mode: Terminate
              hostname: "*.whyredfire.dev"
              namespacePolicy:
                from: All
              certificateRefs:
                - kind: Secret
                  name: wildcard-whyredfire-dev
                  group: ""
            websecure-tech:
              port: 8443
              protocol: HTTPS
              mode: Terminate
              hostname: "*.whyredfire.tech"
              namespacePolicy:
                from: All
              certificateRefs:
                - kind: Secret
                  name: wildcard-whyredfire-tech
                  group: ""
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
